apiVersion: v1
kind: ReplicationController
metadata:
  name: update-controller
  labels:
    state: serving
spec:
  replicas: 1
  selector:
    app: updater
  template:
    metadata:
      labels:
        app: updater
    spec:
      containers:
      - name: backend
        image: us.gcr.io/kinetic-silicon-686/rennt-njt:v2
        env:
        - name: NJ_WORKER
          value: "1"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      dnsPolicy: ClusterFirst

